Template update for nf-core/tools version 3.1.0

diff --git a/.github/workflows/awsfulltest.yml b/.github/workflows/awsfulltest.yml
--- a/.github/workflows/awsfulltest.yml
+++ b/.github/workflows/awsfulltest.yml
@@ -1,11 +1,12 @@
 name: nf-core AWS full size tests
-# This workflow is triggered on PRs opened against the master branch.
+# This workflow is triggered on PRs opened against the main/master branch.
 # It can be additionally triggered manually with GitHub actions workflow dispatch button.
 # It runs the -profile 'test_full' on AWS batch
 
 on:
   pull_request:
     branches:
+      - main
       - master
   workflow_dispatch:
   pull_request_review:
@@ -18,18 +19,30 @@ jobs:
     if: github.repository == 'nf-core/rnaseq' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' || github.event_name == 'workflow_dispatch'
     runs-on: ubuntu-latest
     steps:
-      - uses: octokit/request-action@v2.x
+      - name: Get PR reviews
+        uses: octokit/request-action@v2.x
+        if: github.event_name != 'workflow_dispatch'
         id: check_approvals
+        continue-on-error: true
         with:
-          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
+          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - id: test_variables
+
+      - name: Check for approvals
+        if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
+        run: |
+          echo "No review approvals found. At least 2 approvals are required to run this action automatically."
+          exit 1
+
+      - name: Check for enough approvals (>=2)
+        id: test_variables
         if: github.event_name != 'workflow_dispatch'
         run: |
           JSON_RESPONSE='${{ steps.check_approvals.outputs.data }}'
           CURRENT_APPROVALS_COUNT=$(echo $JSON_RESPONSE | jq -c '[.[] | select(.state | contains("APPROVED")) ] | length')
           test $CURRENT_APPROVALS_COUNT -ge 2 || exit 1 # At least 2 approvals are required
+
       - name: Launch workflow via Seqera Platform
         uses: seqeralabs/action-tower-launch@v2
         # TODO nf-core: You can customise AWS full pipeline tests as required
